#!/usr/bin/env bash
# Display contents of the file `/etc/passwd` using while loop not for/until
# Only displays the username, user id, and user home directory path.

while IFS= read -r passwd;
do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
