#!/usr/bin/env bash
# Parses Apache log files in list format,use awk,not to use while,for,until,cut
#   Displays the IP and HTTP status code from the Apache log file

awk '{print $1 " " $9}' apache-access.log
