#!/usr/bin/env bash
# to print name 9 times the hi on the tenth using while anfif statements

n=0
while [ $n -lt 10 ]
do
	if [ "$count" -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
